ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
