ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
