ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X57/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
