ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-X573/sensor/io
obj-$(CONFIG_MSM_CSIPHY) += msm_csiphy.o
