name: land Kernel Compiler

on: 
  push:
    branches:
      - test-10/main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: jprimero15/archlinux-docker:latest

    steps:
    - uses: actions/checkout@v2
    - name: Building land Kernel
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }} 
      run: |
        wget https://raw.githubusercontent.com/skyhuppa/kernel_test_build/master/build/test.sh
        bash test.sh
  
